-- Compile the LaTeX document
vim.keymap.set('n', '<leader>lc', '<cmd>VimtexCompile<CR>', { desc = '[L]aTeX [C]ompile  document' })

-- Stop the compilation process
vim.keymap.set('n', '<leader>lC', '<cmd>VimtexCompileStop<CR>', { desc = 'Stop [L]aTeX [C]ompile' })

-- View the compiled PDF document
vim.keymap.set('n', '<leader>lv', '<cmd>VimtexView<CR>', { desc = '[L]aTeX [V]iew document' })

-- Toggle the table of contents for the LaTeX document
vim.keymap.set('n', '<leader>lt', '<cmd>VimtexTocToggle<CR>', { desc = '[L]aTeX Toggle [T]OC' })

-- Open the quickfix window to show compilation errors/warnings
vim.keymap.set('n', '<leader>le', '<cmd>VimtexErrors<CR>', { desc = '[L]aTeX compilation [E]rrors' })

-- Clean auxiliary files generated by LaTeX
vim.keymap.set('n', '<leader>lr', '<cmd>VimtexClean<CR>', { desc = '[L]aTeX [R]eset auxiliary files' })

-- Forward search to sync source and PDF (if supported by your PDF viewer)
vim.keymap.set('n', '<leader>ls', '<cmd>VimtexSearch<CR>', { desc = '[L]aTeX [S]ync with zathura' })

-- Insert environment based on surrounding context (e.g., \begin{}...\end{})
vim.keymap.set('n', '<leader>lp', 'vimtex#environment#insert()',
  { expr = true, desc = '[L]aTeX [P]ut environment' })
