vim.keymap.set("n", "<leader>ha", require("harpoon.mark").add_file, { desc = "[H]arpoon [A]dd to list" })
vim.keymap.set("n", "<leader>hm", require("harpoon.ui").toggle_quick_menu, { desc = "[H]arpoon [M]enu open" })
vim.keymap.set("n", "<C-n>", function() require("harpoon.ui").nav_file(1) end)
vim.keymap.set("n", "<C-e>", function() require("harpoon.ui").nav_file(2) end)
vim.keymap.set("n", "<C-i>", function() require("harpoon.ui").nav_file(3) end)
vim.keymap.set("n", "<C-o>", function() require("harpoon.ui").nav_file(4) end)
vim.keymap.set("n", "<C-h>", function() require("harpoon.ui").nav_file(1) end)
vim.keymap.set("n", "<C-j>", function() require("harpoon.ui").nav_file(2) end)
vim.keymap.set("n", "<C-k>", function() require("harpoon.ui").nav_file(3) end)
vim.keymap.set("n", "<C-l>", function() require("harpoon.ui").nav_file(4) end)
